<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>12</LangVersion>
    <AvaloniaUseCompiledBindings>true</AvaloniaUseCompiledBindings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AvaloniaApplication2\AvaloniaApplication2.csproj" />
  </ItemGroup>
  <ItemGroup>
    <AvaloniaResource Include="**\*.axaml" />
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.ReactiveUI" />
    <PackageReference Include="ReactiveUI" />
    <PackageReference Include="ReactiveUI.Avalonia" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
  </ItemGroup>
</Project>